# Generated by Django 3.0.3 on 2020-06-06 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sold', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.DurationField(null=True)),
                ('source', models.GenericIPAddressField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='books.Book')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
